auto: true # automatically rebuilds every time you save
server: true
server_port: 1337 # cause that's how we roll
markdown: maruku
authors: # author details
  andreasbovens:
    display_name: Andreas Bovens
    icon: andreasbovens.jpg
    twitter: andreasbovens
    github: andreasbovens 
  chrismills:
    display_name: Chris Mills
    icon: chrismills.jpg
    twitter: chrisdavidmills
    github: chrisdavidmills
  shwetankdixit:
    display_name: Shwetank Dixit
    icon: shwetankdixit.jpg
    twitter: shwetank
    github: shwetank
